### PR TITLE
Use extension F90 instead of f90 for pre-processed files

### PR DESCRIPTION
**Pull request by kruger**
This is a more natural convention for many compilers and avoids having to manually set compiler flags.

### CODE REVIEW

**Comment by aprokop** [comment]
If that's the case, we may want to update SWIG to generate F90 instead f90, too.

**Comment by sethrj** [comment]
@aprokop I thought about that more and I don't think we should change the default extension since none of the Fortran code SWIG writes requires preprocessing.

@kruger Could you also:
- Change the extensions in `swig/Examples/test-suite/fortran`, 
- Update the `Makefile.in` in that test directory, and
- Remove the `-cpp` flag and comment in `configure.ac` since that should be no longer needed

Thanks!

**Comment by sethrj** [comment]
@aprokop That needs to be done for the build system, but you must also pass a new argument to SWIG using the flags:
```cmake
set(CMAKE_SWIG_FORTRAN_FLAGS "-fext F90")
```

**Comment by aprokop** [comment]
Is this new? I have not seen anything like that in ForTrilinos.

**Comment by sethrj** [comment]
I had to rename all of the files in question to satisfy upstream requirements (on the fortran branch); in the process I updated the extensions to uppercase and changed the relevant gitignore files, build files, etc. Closing this MR.

**Pull request closed without merging**
