### PR TITLE
Add %fortranbegin section

### PR DESCRIPTION
**Pull request by aprokop**
This would allow to insert code in the beginning of a Fortran module
file using `%fortranbegin`, similar how `%begin` inserts the code in the beginning of wrapper.

This is really useful for automatic injection of copyright headers.

### CODE REVIEW

**Comment by youngmit** [comment]
I'm sure this has lots of utility beyond copyright headers, but could the header insertion not also be accomplished with a regular %include?

**Comment by sethrj** [comment]
@youngmit The `%{ %}` block would inject it into the C++ file but not the fortran file.

**Comment by sethrj** [comment]
For consistency with the equivalent Python feature (and with the `%fortranappend` method), can you change this to `%fortranbegin`?

**Comment by aprokop** [comment]
@sethrj Done.

**Comment by aprokop** [comment]
@sethrj I don't understand, why can't I find any code related to this PR in git history? Was the repo force rebased at some point?

**Pull request merged**
